Algoritmo "Lista 04.3 - Exercício6"
//Desenvolver um programa que apresente as potências de 2, variando de 0 a 10.
Var
   // Seção de Declarações das variáveis
   contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Exibindo as potências de 2:")
   para contador de 0 ate 10 passo 1 faca
        escreval("2 elevado à ", contador, " =", 2^contador)
   fimpara

Fimalgoritmo