Algoritmo "Lista 04.3 - Exercício5"
//Desenvolver um programa que apresente todos os números divisíveis por 5 que
//sejam menores que 50.

Var
   // Seção de Declarações das variáveis
   contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("Exibindo todos os núnmeros divisíveis por 5 menores que 50:")
   para contador de 1 ate 49 passo 1 faca
      se (contador % 5 = 0) entao
         escreval(contador)
      fimse
   fimpara

Fimalgoritmo