Algoritmo "Lista 05.1 - Exercício1"
//Desenvolver um programa que exiba os números de 1 a 100

Var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Exibindo os números de 1 a 100")
contador <- 1
enquanto (contador <= 100) faca
         escreval(contador)
         contador <- contador + 1
fimenquanto

Fimalgoritmo